SELECT
  U.ME_USER_ID,
  U.USER_ID,
  U.PASSWORD,
  U.USER_NAME,
  D.DEPARTMENT_NAME,
  U.EMAIL, 
  R.ROLE_NAME,
  U.CREATE_DATE,
  U.STATUS
FROM ME_USER U
LEFT JOIN ME_DEPARTMENT D ON U.DEPT_ID = D.DEPARTMENT_ID
LEFT JOIN ME_ROLE R ON U.ROLE_ID = R.ROLE_ID
WHERE U.STATUS = 'A'
ORDER BY U.USER_ID